// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAljeyI_E9My7LcTAY_khZWw4_zZ_xwgY8',
    appId: '1:1034420320314:web:1313a1df6f7dd332d0dd03',
    messagingSenderId: '1034420320314',
    projectId: 'safespaces-1d7df',
    authDomain: 'safespaces-1d7df.firebaseapp.com',
    storageBucket: 'safespaces-1d7df.appspot.com',
    measurementId: 'G-V3XX5RJHLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjqLI_Him6mWva-5lb29_tN7b-FtK2-34',
    appId: '1:1034420320314:android:2383bf9927d58c27d0dd03',
    messagingSenderId: '1034420320314',
    projectId: 'safespaces-1d7df',
    storageBucket: 'safespaces-1d7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmyXpHl1g7tyqjitPIg2cYy7W5iqKFFU',
    appId: '1:1034420320314:ios:c55b24daf33d162cd0dd03',
    messagingSenderId: '1034420320314',
    projectId: 'safespaces-1d7df',
    storageBucket: 'safespaces-1d7df.appspot.com',
    iosBundleId: 'com.example.safeSpaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmyXpHl1g7tyqjitPIg2cYy7W5iqKFFU',
    appId: '1:1034420320314:ios:c55b24daf33d162cd0dd03',
    messagingSenderId: '1034420320314',
    projectId: 'safespaces-1d7df',
    storageBucket: 'safespaces-1d7df.appspot.com',
    iosBundleId: 'com.example.safeSpaces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAljeyI_E9My7LcTAY_khZWw4_zZ_xwgY8',
    appId: '1:1034420320314:web:06c5b4f5f0151b72d0dd03',
    messagingSenderId: '1034420320314',
    projectId: 'safespaces-1d7df',
    authDomain: 'safespaces-1d7df.firebaseapp.com',
    storageBucket: 'safespaces-1d7df.appspot.com',
    measurementId: 'G-6405DHC2PJ',
  );
}
